name: Generate and Deploy Tables

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OUTPUT_DIR: "tables/html/"

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install markdown

      - name: Run script to generate HTML tables
        run: |
          python << 'EOF'
          import os, re, datetime, markdown

          table_files = [f for f in os.listdir('tables') if f.endswith('.md')]
          table_files.sort(key=lambda x: os.path.getmtime(os.path.join('tables', x)), reverse=True)

          table_list_md = "| Filename | Last Updated |\n|---|---|\n"
          table_list_html = "<table><thead><tr><th>Filename</th><th>Last Updated</th></tr></thead><tbody>"

          for file in table_files:
              file_path = os.path.join('tables', file)
              date_str = datetime.datetime.fromtimestamp(os.path.getmtime(file_path)).strftime('%Y-%m-%d %H:%M:%S')
              file_html = file.replace('.md', '.html')
              
              with open(file_path, 'r', encoding='utf-8') as f:
                  content = f.read()
                  html_content = markdown.markdown(content)
                  os.makedirs('tables/html', exist_ok=True)
                  with open(f'tables/html/{file_html}', 'w', encoding='utf-8') as hf:
                      hf.write(f'<html><body>{html_content}</body></html>')
              
              table_list_md += f"| [{file}](./tables/{file}) | {date_str} |\n"
              table_list_html += f'<tr><td><a href="./tables/html/{file_html}">{file_html}</a></td><td>{date_str}</td></tr>'

          table_list_html += "</tbody></table>"

          with open('README.md', 'r', encoding='utf-8') as f:
              readme = f.read()
          updated_readme = re.sub(r'<!-- TABLE_LIST_START -->.*?<!-- TABLE_LIST_END -->', f"<!-- TABLE_LIST_START -->\n{table_list_md}\n<!-- TABLE_LIST_END -->", readme, flags=re.DOTALL)
          with open('README.md', 'w', encoding='utf-8') as f:
              f.write(updated_readme)

          with open('index.html', 'r', encoding='utf-8') as f:
              html_content = f.read()
          updated_html = re.sub(r'<!-- TABLE_LIST_START -->.*?<!-- TABLE_LIST_END -->', f'<!-- TABLE_LIST_START -->\n{table_list_html}\n<!-- TABLE_LIST_END -->', html_content, flags=re.DOTALL)
          with open('index.html', 'w', encoding='utf-8') as f:
              f.write(updated_html)
          EOF

      - name: Commit and push updates
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md index.html tables/html/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update tables and index [automated]" && git push origin main)

  deploy-pages:
    needs: generate-html
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
